aws s3 cp s3://idl-project-bucket/models/ShuffleNet_1 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_2 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_200 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_201 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_202 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_203 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_204 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_205 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_206 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_207 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_208 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_209 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_3 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_31 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_32 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_33 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_34 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_35 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_36 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_37 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_38 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_39 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_4 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_5 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_6 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_61 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_62 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_63 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_64 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_65 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_66 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_67 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_68 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_69 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_7 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_70 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_71 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_72 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_73 ../models/
aws s3 cp s3://idl-project-bucket/models/ShuffleNet_8 ../models/